create database squiddb;
use squiddb;
CREATE TABLE `blacklist`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Compact;

CREATE TABLE `ipmaster`  (
  `IPID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IPADDRESS` int(12) UNSIGNED NOT NULL,
  `STATUS` tinyint(1) NULL DEFAULT 0,
  `MUL` int(2) UNSIGNED NOT NULL,
  `USED` int(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`IPID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1002 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Compact;

CREATE TABLE `proxymaster`  (
  `PXYID` int(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USERID` int(3) UNSIGNED NOT NULL,
  `IPID` int(4) UNSIGNED NOT NULL,
  `PORT` int(5) UNSIGNED NOT NULL,
  `SDATE` date NOT NULL,
  `STIME` time(0) NOT NULL,
  `EDATE` date NOT NULL,
  `ETIME` time(0) NOT NULL,
  PRIMARY KEY (`PXYID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1001 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Compact;

CREATE TABLE `usermaster`  (
  `USERID` int(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `PASSWORD` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `TYPE` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`USERID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 102 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Compact;

